version: 2

builds:
  - main: ./cmd/tq
    binary: tq
    id: tq
    ldflags:
      - -s -w -X github.com/version-1/tasq/internal/buildinfo.version={{.Version}} -X github.com/version-1/tasq/internal/buildinfo.commit={{.ShortCommit}} -X github.com/version-1/tasq/internal/config.defaultHomeProfile={{.Env.TQ_BUILD_PROFILE}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - main: ./cmd/issue-tracker
    binary: issue-tracker
    id: issue-tracker
    ldflags:
      - -s -w -X github.com/version-1/tasq/internal/config.defaultHomeProfile={{.Env.TQ_BUILD_PROFILE}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - main: ./cmd/orchestrator
    binary: orchestrator
    id: orchestrator
    ldflags:
      - -s -w -X github.com/version-1/tasq/internal/config.defaultHomeProfile={{.Env.TQ_BUILD_PROFILE}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - main: ./cmd/web
    binary: web
    id: web
    ldflags:
      - -s -w -X github.com/version-1/tasq/internal/buildinfo.version={{.Version}} -X github.com/version-1/tasq/internal/buildinfo.commit={{.ShortCommit}} -X github.com/version-1/tasq/internal/config.defaultHomeProfile={{.Env.TQ_BUILD_PROFILE}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

release:
  prerelease: auto
